server:
  port: 9000
spring:
  application:
    name: tensorflow-kotlin-example
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoint:
    health:
      enabled: true
model:
  directory: ${MODEL_DIRECTORY}